server:
  port: 6888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVER_PASSWORD:default}
